version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
  jobs:
  build_and_test:
    steps:
      - checkout
      - run:
          command: mvn test
          name: Run tests
      - run:
          command: mvn build
          name: Build app


